export const MEAT_AND_MEAT_PRODUCTS = 'MEAT_AND_MEAT_PRODUCTS';
export const BUTTER_OR_CREAM = 'BUTTER_OR_CREAM';
export const OILS_FATS_MARGARINE = 'OILS_FATS_MARGARINE';
export const ALCOHOL_BELOW_18 = 'ALCOHOL_BELOW_18';
export const ALCOHOL_ABOVE_18 = 'ALCOHOL_ABOVE_18';
export const CIGARETTES_AND_CIGARS = 'CIGARETTES_AND_CIGARS';
export const OTHER_TOBACCO = 'OTHER_TOBACCO';

export const emptyBasket = {
  [MEAT_AND_MEAT_PRODUCTS]: 0,
  [BUTTER_OR_CREAM]: 0,
  [OILS_FATS_MARGARINE]: 0,
  [ALCOHOL_BELOW_18]: 0,
  [ALCOHOL_ABOVE_18]: 0,
  [CIGARETTES_AND_CIGARS]: 0,
  [OTHER_TOBACCO]: 0,
};
