// @flow
import type { Categories, CategoriesList } from '../types/basket';

// CATEGORIES and CATEGORIES_LIST are the two base objects containing
// all the categories. If a new category needs to be added, it is added to
// both of these objects

export const CATEGORIES: Categories = {
  MEAT_AND_MEAT_PRODUCTS: 'MEAT_AND_MEAT_PRODUCTS',
  BUTTER_OR_CREAM: 'BUTTER_OR_CREAM',
  OILS_FATS_MARGARINE: 'OILS_FATS_MARGARINE',
  OTHER_FOODS: 'OTHER_FOODS',
  ALCOHOL_BELOW_18: 'ALCOHOL_BELOW_18',
  ALCOHOL_ABOVE_18: 'ALCOHOL_ABOVE_18',
  CIGARETTES_AND_CIGARS: 'CIGARETTES_AND_CIGARS',
  OTHER_TOBACCO: 'OTHER_TOBACCO',
  MEDICINE: 'MEDICINE',
  BOOKS: 'BOOKS',
  MAGAZINES: 'MAGAZINES',
  FLOWERS_AND_PLANTS: 'FLOWERS_AND_PLANTS',
  ANIMAL_FEED: 'ANIMAL_FEED',
  FERTILIZER: 'FERTILIZER',
  OTHER_GOODS: 'OTHER_GOODS',
};

export const CATEGORIES_LIST: CategoriesList = [
  CATEGORIES.MEAT_AND_MEAT_PRODUCTS,
  CATEGORIES.BUTTER_OR_CREAM,
  CATEGORIES.OILS_FATS_MARGARINE,
  CATEGORIES.OTHER_FOODS,
  CATEGORIES.ALCOHOL_BELOW_18,
  CATEGORIES.ALCOHOL_ABOVE_18,
  CATEGORIES.CIGARETTES_AND_CIGARS,
  CATEGORIES.OTHER_TOBACCO,
  CATEGORIES.MEDICINE,
  CATEGORIES.BOOKS,
  CATEGORIES.MAGAZINES,
  CATEGORIES.FLOWERS_AND_PLANTS,
  CATEGORIES.ANIMAL_FEED,
  CATEGORIES.FERTILIZER,
  CATEGORIES.OTHER_GOODS,
];
