// @flow

export const currencyPicker: Array<{
  label: string,
  value: string,
  flag: string,
}> = [
  { label: ' 🇪🇺 EUR', flag: '🇪🇺', value: 'EUR' },
  { label: ' 🇺🇸 USD', flag: '🇺🇸', value: 'USD' },
  { label: ' 🇨🇭 CHF', flag: '🇨🇭', value: 'CHF' },
  { label: ' 🇦🇪 AED', flag: '🇦🇪', value: 'AED' },
  { label: ' 🇦🇱 ALL', flag: '🇦🇱', value: 'ALL' },
  { label: ' 🇦🇷 ARS', flag: '🇦🇷', value: 'ARS' },
  { label: ' 🇦🇺 AUD', flag: '🇦🇺', value: 'AUD' },
  { label: ' 🇦🇿 AZN', flag: '🇦🇿', value: 'AZN' },
  { label: ' 🇧🇦 BAM', flag: '🇦🇿', value: 'BAM' },
  { label: ' 🇧🇩 BDT', flag: '🇧🇩', value: 'BDT' },
  { label: ' 🇧🇬 BGN', flag: '🇧🇬', value: 'BGN' },
  { label: ' 🇧🇭 BHD', flag: '🇧🇭', value: 'BHD' },
  { label: ' 🇧🇷 BRL', flag: '🇧🇷', value: 'BRL' },
  { label: ' 🇨🇦 CAD', flag: '🇨🇦', value: 'CAD' },
  { label: ' 🇨🇱 CLP', flag: '🇨🇱', value: 'CLP' },
  { label: ' 🇨🇳 CNY', flag: '🇨🇳', value: 'CNY' },
  { label: ' 🇨🇴 COP', flag: '🇨🇴', value: 'COP' },
  { label: ' 🇨🇷 CRC', flag: '🇨🇷', value: 'CRC' },
  { label: ' 🇨🇿 CZK', flag: '🇨🇿', value: 'CZK' },
  { label: ' 🇩🇰 DKK', flag: '🇩🇰', value: 'DKK' },
  { label: ' 🇩🇴 DOP', flag: '🇩🇴', value: 'DOP' },
  { label: ' 🇪🇬 EGP', flag: '🇪🇬', value: 'EGP' },
  { label: ' 🇪🇹 ETB', flag: '🇪🇹', value: 'ETB' },
  { label: ' 🇬🇧 GBP', flag: '🇬🇧', value: 'GBP' },
  { label: ' 🇬🇹 GTQ', flag: '🇬🇹', value: 'GTQ' },
  { label: ' 🇭🇰 HKD', flag: '🇭🇰', value: 'HKD' },
  { label: ' 🇭🇳 HNL', flag: '🇭🇳', value: 'HNL' },
  { label: ' 🇭🇷 HRK', flag: '🇭🇷', value: 'HRK' },
  { label: ' 🇭🇺 HUF', flag: '🇭🇺', value: 'HUF' },
  { label: ' 🇮🇩 IDR', flag: '🇮🇩', value: 'IDR' },
  { label: ' 🇮🇱 ILS', flag: '🇮🇱', value: 'ILS' },
  { label: ' 🇮🇳 INR', flag: '🇮🇳', value: 'INR' },
  { label: ' 🇮🇸 ISK', flag: '🇮🇸', value: 'ISK' },
  { label: ' 🇯🇵 JPY', flag: '🇯🇵', value: 'JPY' },
  { label: ' 🇰🇪 KES', flag: '🇰🇪', value: 'KES' },
  { label: ' 🇰🇭 KHR', flag: '🇰🇭', value: 'KHR' },
  { label: ' 🇰🇷 KRW', flag: '🇰🇷', value: 'KRW' },
  { label: ' 🇰🇼 KWD', flag: '🇰🇼', value: 'KWD' },
  { label: ' 🇰🇾 KYD', flag: '🇰🇾', value: 'KYD' },
  { label: ' 🇰🇿 KZT', flag: '🇰🇿', value: 'KZT' },
  { label: ' 🇱🇧 LBP', flag: '🇱🇧', value: 'LBP' },
  { label: ' 🇱🇰 LKR', flag: '🇱🇰', value: 'LKR' },
  { label: ' 🇱🇾 LYD', flag: '🇱🇾', value: 'LYD' },
  { label: ' 🇲🇦 MAD', flag: '🇲🇦', value: 'MAD' },
  { label: ' 🇲🇺 MUR', flag: '🇲🇺', value: 'MUR' },
  { label: ' 🇲🇽 MXN', flag: '🇲🇽', value: 'MXN' },
  { label: ' 🇲🇾 MYR', flag: '🇲🇾', value: 'MYR' },
  { label: ' 🇳🇬 NGN', flag: '🇳🇬', value: 'NGN' },
  { label: ' 🇳🇴 NOK', flag: '🇳🇴', value: 'NOK' },
  { label: ' 🇳🇿 NZD', flag: '🇳🇿', value: 'NZD' },
  { label: ' 🇴🇲 OMR', flag: '🇴🇲', value: 'OMR' },
  { label: ' 🇵🇦 PAB', flag: '🇵🇦', value: 'PAB' },
  { label: ' 🇵🇪 PEN', flag: '🇵🇪', value: 'PEN' },
  { label: ' 🇵🇭 PHP', flag: '🇵🇭', value: 'PHP' },
  { label: ' 🇵🇰 PKR', flag: '🇵🇰', value: 'PKR' },
  { label: ' 🇵🇱 PLN', flag: '🇵🇱', value: 'PLN' },
  { label: ' 🇶🇦 QAR', flag: '🇶🇦', value: 'QAR' },
  { label: ' 🇷🇴 RON', flag: '🇷🇴', value: 'RON' },
  { label: ' 🇷🇸 RSD', flag: '🇷🇸', value: 'RSD' },
  { label: ' 🇷🇺 RUB', flag: '🇷🇺', value: 'RUB' },
  { label: ' 🇸🇦 SAR', flag: '🇸🇦', value: 'SAR' },
  { label: ' 🇸🇪 SEK', flag: '🇸🇪', value: 'SEK' },
  { label: ' 🇸🇬 SGD', flag: '🇸🇬', value: 'SGD' },
  { label: ' 🇹🇭 THB', flag: '🇹🇭', value: 'THB' },
  { label: ' 🇹🇳 TND', flag: '🇹🇳', value: 'TND' },
  { label: ' 🇹🇷 TRY', flag: '🇹🇷', value: 'TRY' },
  { label: ' 🇹🇼 TWD', flag: '🇹🇼', value: 'TWD' },
  { label: ' 🇹🇿 TZS', flag: '🇹🇿', value: 'TZS' },
  { label: ' 🇺🇦 UAH', flag: '🇺🇦', value: 'UAH' },
  { label: ' 🇺🇾 UYU', flag: '🇺🇾', value: 'UYU' },
  { label: ' 🇻🇪 VEF', flag: '🇻🇪', value: 'VEF' },
  { label: ' 🇻🇳 VND', flag: '🇻🇳', value: 'VND' },
  { label: ' 🇿🇦 ZAR', flag: '🇿🇦', value: 'ZAR' },
];
