export const dutyFreeAllowances = {
  MEAT_AND_MEAT_PRODUCTS: 1,
  BUTTER_OR_CREAM: 1,
  OILS_FATS_MARGARINE: 5,
  ALCOHOL_BELOW_18: 5,
  ALCOHOL_ABOVE_18: 1,
  CIGARETTES_AND_CIGARS: 250,
  OTHER_TOBACCO: 250,
};

export const dutyRates = {
  MEAT_AND_MEAT_PRODUCTS_FIRST_DUTY_THRESHOLD: 10,
  MEAT_AND_MEAT_PRODUCTS_DUTY_UNDER_THRESHOLD: 17,
  MEAT_AND_MEAT_PRODUCTS_DUTY_OVER_THRESHOLD: 23,
  BUTTER_OR_CREAM_DUTY: 16,
  OILS_FATS_MARGARINE_DUTY: 2,
  ALCOHOL_BELOW_18_DUTY: 2,
  ALCOHOL_ABOVE_18_DUTY: 15,
  CIGARETTES_AND_CIGARS_DUTY: 0.25,
  OTHER_TOBACCO_DUTY: 0.1,
};
